[package]
name = "tan_lsp_server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
lsp-types = "0.93"
lsp-server = "0.6"
clap = "4"
tracing = "0.1"
tracing-subscriber = "0.2"
serde = { version = "1", features = ["derive"]}
serde_json = "1"
tan_lsp = { path = "tan_lsp" }
